#
# Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
# Creation Date: Sun Jan 25 05:59:18 PST 2015
# Last Modified: Wed Jan 28 22:15:40 PST 2015
# Filename:      scorelib/_includes/docslot/Makefile
# Syntax:        GNU Makefile
#
# Description:   Fill in short descriptions of functions in index files.
#


all: 
	./processFiles [A-Z]*.html


