#
# Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
# Creation Date: Sun Feb  8 21:39:37 PST 2015
# Last Modified: Sun Feb  8 21:39:40 PST 2015
# Filename:      scorelib/class/Makefile.class
# Syntax:        GNU Makefile
#
# Description:   Fill in the source code line ranges from the current
#                version of the scorelib source code on GitHub.
#

BINDIR = ../../bin

all: lines

lines:
	$(BINDIR)/insertCodeLines *.aton


